# Generated by Django 6.0 on 2025-12-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overtimeentry',
            unique_together={('employee', 'date')},
        ),
    ]
